services:
  postgres:
    image: postgres:16-alpine
    container_name: artshop_db
    restart: unless-stopped # Redémarre auto sauf arrêt manuel
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Données persistantes

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest    # Interface web moderne pour BDD
    container_name: artshop_cloudbeaver
    restart: unless-stopped
    ports:
      - "8080:8978"                      # Accessible sur localhost:8080
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace  # Config persistante
    depends_on:
      - postgres

volumes:
  postgres_data:
  cloudbeaver_data: